### ISSUE TITLE
Edit getRoute() for "/" case

### ISSUE THREAD

**Issue by DimiOui** [ouafabulous/webserv_42#15]

**Comment by DimiOui** [comment]
```nginx
server {
  root    /var/www;
  location    / {
    root /var/html;
  }
}
```
`curl localhost/index.html` will print `/var/www/index.html`.

**Comment by ouafabulous** [comment]
Default location is recorded with an empty string as location value. 
If there is a location with /, it will be recorded with "/".
So basically in the getRoute, we'll try to fetch "/", untill it doesn't exist, then it fetches "".
