### ISSUE TITLE
getError should be integrated in Poll

### ISSUE THREAD

**Issue by ouafabulous** [ouafabulous/webserv_42#38]

**Comment by misteriaud** [comment]
Fix with https://github.com/ouafabulous/webserv_42/commit/32d405df3a32051bd7161e6c5b95430c74cbfed1

**Comment by misteriaud** [comment]
Fix in this commit : https://github.com/ouafabulous/webserv_42/commit/32d405df3a32051bd7161e6c5b95430c74cbfed1
